bootstrap:
  server:
    host: localhost:9092
key:
  serializer:
    binary: org.apache.kafka.common.serialization.StringSerializer
    string: org.apache.kafka.common.serialization.StringSerializer
value:
  serializer:
    binary: org.apache.kafka.common.serialization.ByteArraySerializer
    string: org.apache.kafka.common.serialization.StringSerializer
linger:
  ms: 200